<?php
$cars = [
    [
        "id" => 1,
        "marca" => "Opel",
        "modello" => "Signum",
        "versione" => null,
        "prezzo" => 500,
        "carrozzeria" => "Station wagon",
        "anno" => 2003,
        "carburante" => "Diesel",
        "chilometraggio" => 264783,
        "potenza" => "92 kW 125 CV",
        "cambio" => "Manuale",
        "n_marce" => 5,
        "n_porte" => 5,
        "n_posti" => 5,
        "condizioni" => "Usato",
        "equipaggiamento" => "Alzacristalli elettrici, Bracciolo, Climatizzatore, Climatizzatore automatico 2 zone, Sedili riscaldati, Specchietti laterali elettrici, Volante multifunzione, Cerchi in lega, ABS, Airbag conducente, Airbag passeggero, Chiusura centralizzata, Fendinebbia, Servosterzo",
        "colore_carrozzeria" => "Grigio",
        "colore_interni" => "Nero",
        "n_proprietari" => 1,
        "classe_emissioni" => "Euro 3",
    ],
    [
        "id" => 2,
        "marca" => "Mercedes-Benz",
        "modello" => "A 170",
        "versione" => null,
        "prezzo" => 700,
        "carrozzeria" => "Berlina",
        "anno" => 1999,
        "carburante" => "Diesel",
        "chilometraggio" => 383779,
        "potenza" => "66 kW 90 CV",
        "cambio" => "Manuale",
        "n_marce" => 5,
        "n_porte" => 5,
        "n_posti" => 5,
        "condizioni" => "Usato",
        "equipaggiamento" => "Alzacristalli elettrici, Bracciolo, Climatizzatore, Sedile posteriore sdoppiato, Specchietti laterali elettrici, Autoradio, Cerchi in lega, ABS, Airbag conducente, Airbag laterali, Airbag passeggero, Chiusura centralizzata, Controllo automatico trazione, Servosterzo",
        "colore_carrozzeria" => "Blu",
        "colore_interni" => "Nero",
        "n_proprietari" => 1,
        "classe_emissioni" => "Euro 3",
    ],
    [
        "id" => 3,
        "marca" => "Toyota",
        "modello" => "Yaris",
        "versione" => null,
        "prezzo" => 1500,
        "carrozzeria" => "City car",
        "anno" => 2005,
        "carburante" => "Benzina",
        "chilometraggio" => 129000,
        "potenza" => "48 kW 65 CV",
        "cambio" => "Manuale",
        "n_marce" => 5,
        "n_porte" => 5,
        "n_posti" => 5,
        "condizioni" => "Usato",
        "equipaggiamento" => "Alzacristalli elettrici, Specchietti laterali elettrici, Volante in pelle, Autoradio, MP3, Sound system, Luce d'ambiente, Airbag conducente, Airbag laterali, Airbag passeggero, Chiusura centralizzata, Chiusura centralizzata telecomandata, Immobilizzatore elettronico, Isofix, Servosterzo, Sistema di avviso di distanza",
        "colore_carrozzeria" => "Grigio",
        "colore_interni" => "Nero",
        "n_proprietari" => 1,
        "classe_emissioni" => null,
    ],
    [
        "id" => 4,
        "marca" => "Porsche",
        "modello" => "997",
        "versione" => null,
        "prezzo" => 349000,
        "carrozzeria" => "Cabrio",
        "anno" => 2011,
        "carburante" => "Benzina",
        "chilometraggio" => 4000,
        "potenza" => "300 kW 408 CV",
        "cambio" => "Automatico",
        "n_marce" => 6,
        "n_porte" => 2,
        "n_posti" => 2,
        "condizioni" => "Usato",
        "equipaggiamento" => "Alzacristalli elettrici, Bracciolo, Climatizzatore, Controllo automatico clima, Cruise Control, Regolazione elettrica sedili, Sedile posteriore sdoppiato, Sedili ventilati, Sensore di pioggia, Specchietti laterali elettrici, Start/Stop Automatico, Tettuccio apribile, Volante in pelle, Android Auto, Apple CarPlay, Autoradio digitale, Bluetooth, Computer di bordo, Sound system, USB, Cerchi in lega, Controllo vocale, Leve al volante, Sistema lavafari, Touch screen, ABS, Airbag conducente, Airbag laterali, Airbag passeggero, Antifurto, Chiusura centralizzata, Chiusura centralizzata telecomandata, Controllo automatico trazione, ESP, Fari direzionali, Fari LED, Fendinebbia, Immobilizzatore elettronico, Servosterzo",
        "colore_carrozzeria" => "Azzurro",
        "colore_interni" => "Nero",
        "n_proprietari" => 1,
        "classe_emissioni" => "Euro 5",
    ],
];
?>